package com.example.Student_Library_Management_System.Models;

import com.example.Student_Library_Management_System.Enums.CardStatus;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import javax.xml.crypto.Data;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity
@Table(name = "card")
public class Card {

    //Plan is to save this card in Db
    //Before saving I have to set its attribute : Rule1

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;   //Its auto generated

    @CreationTimestamp //Auto timestamp the time when an entry is created
    private Date createedOn;     //Its is auto generated

    @UpdateTimestamp  //Sets time when an entry is updated
    private Date updatedOn;   //Its is autogenerated

    @Enumerated(value = EnumType.STRING)
    private CardStatus cardStatus;   //Set this attrubute


    @OneToOne
    @JoinColumn
     private Student studentVariableName;   //This variableis used in the parent class
    // while doing the bidirectional mapping

    //Card is parent wrt to book
    @OneToMany(mappedBy = "card",cascade = CascadeType.ALL)
    List<Book> booksIssued = new ArrayList<>();





    public Student getStudentVariableName() {
        return studentVariableName;
    }

    public void setStudentVariableName(Student studentVariableName) {
        this.studentVariableName = studentVariableName;
    }

    public Card() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getCreateedOn() {
        return createedOn;
    }

    public void setCreateedOn(Date createedOn) {
        this.createedOn = createedOn;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public CardStatus getCardStatus() {
        return cardStatus;
    }

    public void setCardStatus(CardStatus cardStatus) {
        this.cardStatus = cardStatus;
    }
}
